package com.changh.exchange.entity.core;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.changh.exchange.entity.sms.ContentTemplet;
import com.changh.exchange.entity.util.SiteCount;
import com.reagan.core.annotation.Mapper;

/**
 * CoreActivities generated by hbm2java
 */
@Mapper(tableName="core_activities")
public class Activities implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9133137371958220161L;
	@Mapper(column="a_id", updateWhere=true)
	private Long AId;
	@Mapper(column="a_organization_id", update=true)
	private Long organizationId;
	@Mapper(column="a_strategy_id", update=true)
	private Long strategyId;
	@Mapper(column="a_name", update=true, like=true)
	private String AName;
	@Mapper(column="a_start_date", update=true)
	private Date AStartDate;
	@Mapper(column="a_end_date", update=true)
	private Date AEndDate;
	@Mapper(column="a_code", update=true)
	private String ACode;
	private List<ContentTemplet> contentTemplets = new ArrayList<ContentTemplet>(
			0);
	private List<SiteCount> siteCounts = new ArrayList<SiteCount>(0);
	private List<VoucherStrategy> voucherStrategies = new ArrayList<VoucherStrategy>(
			0);

	public Long getAId() {
		return this.AId;
	}

	public void setAId(Long AId) {
		this.AId = AId;
	}


	public String getAName() {
		return this.AName;
	}

	public void setAName(String AName) {
		this.AName = AName;
	}

	public Date getAStartDate() {
		return this.AStartDate;
	}

	public void setAStartDate(Date AStartDate) {
		this.AStartDate = AStartDate;
	}

	public Date getAEndDate() {
		return this.AEndDate;
	}

	public void setAEndDate(Date AEndDate) {
		this.AEndDate = AEndDate;
	}

	public Long getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	public Long getStrategyId() {
		return strategyId;
	}

	public void setStrategyId(Long strategyId) {
		this.strategyId = strategyId;
	}

	public List<ContentTemplet> getContentTemplets() {
		return contentTemplets;
	}

	public void setSmsContentTemplets(List<ContentTemplet> contentTemplets) {
		this.contentTemplets = contentTemplets;
	}

	public List<SiteCount> getSiteCounts() {
		return siteCounts;
	}

	public void setSiteCounts(List<SiteCount> siteCounts) {
		this.siteCounts = siteCounts;
	}

	public void setContentTemplets(List<ContentTemplet> contentTemplets) {
		this.contentTemplets = contentTemplets;
	}

	public List<VoucherStrategy> getVoucherStrategies() {
		return voucherStrategies;
	}

	public void setVoucherStrategies(
			List<VoucherStrategy> voucherStrategies) {
		this.voucherStrategies = voucherStrategies;
	}

	public String getACode() {
		return ACode;
	}

	public void setACode(String aCode) {
		ACode = aCode;
	}

}
