package com.changh.exchange.entity.core;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.reagan.core.annotation.Mapper;

/**
 * CoreVoucherStrategy generated by hbm2java
 */
@Mapper(tableName="core_voucher_strategy")
public class VoucherStrategy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2123277852410080917L;
	@Mapper(column="s_id", updateWhere=true)
	private Long SId;
	@Mapper(column="s_organization_id", update=true)
	private Long organizationId;
	@Mapper(column="s_name", update=true, like=true)
	private String SName;
	@Mapper(column="s_description", update=true)
	private String SDescription;
	@Mapper(column="s_voucher_type", update=true)
	private Integer SVoucherType;
	@Mapper(column="s_voucher_count", update=true)
	private Integer SVoucherCount;
	@Mapper(column="s_create_name")
	private String SCreateName;
	@Mapper(column="s_create_date")
	private Date SCreateDate;
	@Mapper(column="s_voucher_use_count", update=true)
	private Integer SVoucherUseCount;
	private List<Voucher> vouchers = new ArrayList<Voucher>(0);

	public Long getSId() {
		return this.SId;
	}

	public void setSId(Long SId) {
		this.SId = SId;
	}

	public String getSName() {
		return this.SName;
	}

	public void setSName(String SName) {
		this.SName = SName;
	}

	public String getSDescription() {
		return this.SDescription;
	}

	public void setSDescription(String SDescription) {
		this.SDescription = SDescription;
	}

	public Integer getSVoucherType() {
		return this.SVoucherType;
	}

	public void setSVoucherType(Integer SVoucherType) {
		this.SVoucherType = SVoucherType;
	}

	public Integer getSVoucherCount() {
		return this.SVoucherCount;
	}

	public void setSVoucherCount(Integer SVoucherCount) {
		this.SVoucherCount = SVoucherCount;
	}

	public String getSCreateName() {
		return this.SCreateName;
	}

	public void setSCreateName(String SCreateName) {
		this.SCreateName = SCreateName;
	}

	public Date getSCreateDate() {
		return this.SCreateDate;
	}

	public void setSCreateDate(Date SCreateDate) {
		this.SCreateDate = SCreateDate;
	}

	public Integer getSVoucherUseCount() {
		return this.SVoucherUseCount;
	}

	public void setSVoucherUseCount(Integer SVoucherUseCount) {
		this.SVoucherUseCount = SVoucherUseCount;
	}

	public Long getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	public List<Voucher> getVouchers() {
		return vouchers;
	}

	public void setVouchers(List<Voucher> vouchers) {
		this.vouchers = vouchers;
	}

}
