package com.changh.exchange.entity.util;

import com.reagan.core.annotation.Mapper;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

/**
 * UtilSequenceId generated by hbm2java
 */
@Mapper(tableName="util_sequence")
public class Sequence implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = -144154162670987077L;
	@Mapper(column="s_id", insert=false, updateWhere=true)
	private int Sid;
	@Mapper(column="s_value")
	private String SValue;

	public int getSid() {
		return Sid;
	}

	public void setSid(int sid) {
		Sid = sid;
	}

	public String getSValue() {
		return this.SValue;
	}

	public void setSValue(String SValue) {
		this.SValue = SValue;
	}

}
