package com.changh.exchange.entity.util;

import com.reagan.core.annotation.Mapper;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

/**
 * UtilSiteCount generated by hbm2java
 */
@Mapper(tableName="util_site_count")
public class SiteCount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5285508603351444498L;
	@Mapper(column="w_site_url", updateWhere=true)
	private int WSiteUrl;
	@Mapper(column="w_activities_id")
	private int activitieId;
	@Mapper(column="w_organization_id")
	private int organizationId;
	@Mapper(column="w_view_count", update=true)
	private int WViewCount;
	public int getWSiteUrl() {
		return WSiteUrl;
	}
	public void setWSiteUrl(int wSiteUrl) {
		WSiteUrl = wSiteUrl;
	}
	public int getActivitieId() {
		return activitieId;
	}
	public void setActivitieId(int activitieId) {
		this.activitieId = activitieId;
	}
	public int getOrganizationId() {
		return organizationId;
	}
	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}
	public int getWViewCount() {
		return WViewCount;
	}
	public void setWViewCount(int wViewCount) {
		WViewCount = wViewCount;
	}
	
}
