package com.changh.exchange.entity.util;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.reagan.core.annotation.Mapper;

/**
 * UtilVoucherVerifyLog generated by hbm2java
 */
@Mapper(tableName="util_voucher_verify_log")
public class VoucherVerifyLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 511644325648361855L;
	@Mapper(column="v_id", updateWhere=true)
	private int VId;
	@Mapper(column="v_voucher_id")
	private Integer VVoucherId;
	@Mapper(column="v_verify_date")
	private Date VVerifyDate;
	@Mapper(column="v_code")
	private String VCode;
	@Mapper(column="v_organization_id")
	private Integer VOrganizationId;

	public int getVId() {
		return this.VId;
	}

	public void setVId(int VId) {
		this.VId = VId;
	}

	public Integer getVVoucherId() {
		return this.VVoucherId;
	}

	public void setVVoucherId(Integer VVoucherId) {
		this.VVoucherId = VVoucherId;
	}

	public Date getVVerifyDate() {
		return this.VVerifyDate;
	}

	public void setVVerifyDate(Date VVerifyDate) {
		this.VVerifyDate = VVerifyDate;
	}

	public String getVCode() {
		return this.VCode;
	}

	public void setVCode(String VCode) {
		this.VCode = VCode;
	}

	public Integer getVOrganizationId() {
		return this.VOrganizationId;
	}

	public void setVOrganizationId(Integer VOrganizationId) {
		this.VOrganizationId = VOrganizationId;
	}

}
