package com.changh.exchange.entity.sms;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.reagan.core.annotation.Mapper;


/**
 * SmsContentTemplet generated by hbm2java
 */
@Mapper(tableName="sms_content_templet")
public class ContentTemplet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8220420582914061285L;
	@Mapper(column="t_id", updateWhere=true)
	private Long TId;
	@Mapper(column="t_activities_id", update=true)
	private Long activitieId;
	@Mapper(column="t_content", update=true)
	private String TContent;
	@Mapper(column="t_create_date", update=true)
	private Date TCreateDate;
	@Mapper(column="t_send_count", update=true)
	private Integer TSendCount;
	@Mapper(column="t_success_count", update=true)
	private Integer TSuccessCount;
	@Mapper(column="t_failure_count", update=true)
	private Integer TFailureCount;
	private List<SMS> sends = new ArrayList<SMS>(0);

	public Long getTId() {
		return this.TId;
	}

	public void setTId(Long TId) {
		this.TId = TId;
	}

	public String getTContent() {
		return this.TContent;
	}

	public void setTContent(String TContent) {
		this.TContent = TContent;
	}

	public Date getTCreateDate() {
		return this.TCreateDate;
	}

	public void setTCreateDate(Date TCreateDate) {
		this.TCreateDate = TCreateDate;
	}

	public Integer getTSendCount() {
		return this.TSendCount;
	}

	public void setTSendCount(Integer TSendCount) {
		this.TSendCount = TSendCount;
	}

	public Integer getTSuccessCount() {
		return this.TSuccessCount;
	}

	public void setTSuccessCount(Integer TSuccessCount) {
		this.TSuccessCount = TSuccessCount;
	}

	public Integer getTFailureCount() {
		return this.TFailureCount;
	}

	public void setTFailureCount(Integer TFailureCount) {
		this.TFailureCount = TFailureCount;
	}

	public Long getActivitieId() {
		return activitieId;
	}

	public void setActivitieId(Long activitieId) {
		this.activitieId = activitieId;
	}

	public List<SMS> getSends() {
		return sends;
	}

	public void setSends(List<SMS> sends) {
		this.sends = sends;
	}

}
