package com.changh.exchange.entity.sms;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import com.reagan.core.annotation.Mapper;

/**
 * SmsSendId generated by hbm2java
 */
@Mapper(tableName="sms_send")
public class SMS implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7011004245656541772L;
	@Mapper(column="s_id")
	private Long SId;
	@Mapper(column="s_content_id")
	private Long SContentId;
	@Mapper(column="s_mobile_number", updateWhere=true)
	private String SMobileNumber;
	@Mapper(column="s_seq_id", updateWhere=true)
	private Long SSeqId;
	@Mapper(column="s_send_date", update=true)
	private String SSendDate;
	@Mapper(column="s_revice_date", update=true)
	private String SReviceDate;
	@Mapper(column="s_error_code", update=true)
	private String SErrorCode;
	@Mapper(column="s_report_status", update=true)
	private Integer SReportStatus;


	public Long getSId() {
		return this.SId;
	}

	public void setSId(Long SId) {
		this.SId = SId;
	}

	public Long getSContentId() {
		return this.SContentId;
	}

	public void setSContentId(Long SContentId) {
		this.SContentId = SContentId;
	}

	public String getSMobileNumber() {
		return this.SMobileNumber;
	}

	public void setSMobileNumber(String SMobileNumber) {
		this.SMobileNumber = SMobileNumber;
	}

	public Long getSSeqId() {
		return this.SSeqId;
	}

	public void setSSeqId(Long SSeqId) {
		this.SSeqId = SSeqId;
	}

	public String getSSendDate() {
		return this.SSendDate;
	}

	public void setSSendDate(String SSendDate) {
		this.SSendDate = SSendDate;
	}

	public String getSReviceDate() {
		return this.SReviceDate;
	}

	public void setSReviceDate(String SReviceDate) {
		this.SReviceDate = SReviceDate;
	}

	public String getSErrorCode() {
		return this.SErrorCode;
	}

	public void setSErrorCode(String SErrorCode) {
		this.SErrorCode = SErrorCode;
	}

	public Integer getSReportStatus() {
		return this.SReportStatus;
	}

	public void setSReportStatus(Integer SReportStatus) {
		this.SReportStatus = SReportStatus;
	}

}
