package com.changh.exchange.entity.common;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.reagan.core.annotation.Mapper;

/**
 * CommonManager generated by hbm2java
 */
@Mapper(tableName="common_manager")
public class Manager implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4935758375195606229L;
	@Mapper(column="m_id", updateWhere=true)
	private Long MId;
	@Mapper(column="m_role_id", update=true)
	private Long roleId;
	@Mapper(column="m_organization_id", update=true)
	private Long organizationId;
	@Mapper(column="m_username")
	private String MUsername;
	@Mapper(column="m_password", update=true)
	private String MPassword;
	@Mapper(column="m_create_date")
	private Date MCreateDate;
	//0.无效 1.有效
	@Mapper(column="m_status", update=true)
	private Integer MStatus;

	public Long getMId() {
		return this.MId;
	}

	public void setMId(Long MId) {
		this.MId = MId;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public Long getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(Long organizationId) {
		this.organizationId = organizationId;
	}

	public String getMUsername() {
		return this.MUsername;
	}

	public void setMUsername(String MUsername) {
		this.MUsername = MUsername;
	}

	public String getMPassword() {
		return this.MPassword;
	}

	public void setMPassword(String MPassword) {
		this.MPassword = MPassword;
	}

	public Date getMCreateDate() {
		return this.MCreateDate;
	}

	public void setMCreateDate(Date MCreateDate) {
		this.MCreateDate = MCreateDate;
	}

	public Integer getMStatus() {
		return MStatus;
	}

	public void setMStatus(Integer mStatus) {
		MStatus = mStatus;
	}

}
