package com.changh.exchange.entity.common;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import com.changh.exchange.entity.core.Activities;
import com.changh.exchange.entity.core.VoucherStrategy;
import com.changh.exchange.entity.util.SiteCount;
import com.reagan.core.annotation.Mapper;

/**
 * CommonOrganization generated by hbm2java
 */
@Mapper(tableName="common_organization")
public class Organization implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1913909024691639413L;
	@Mapper(column="o_id", updateWhere=true)
	private Long OId;
	@Mapper(column="o_name", update=true, like=true)
	private String OName;
	@Mapper(column="o_city", update=true)
	private String OCity;
	@Mapper(column="o_district", update=true)
	private String ODistrict;
	@Mapper(column="o_address", update=true)
	private String OAddress;
	@Mapper(column="o_tel", update=true)
	private String OTel;
	@Mapper(column="o_zipcode", update=true)
	private String OZipcode;
	@Mapper(column="o_linkman", update=true)
	private String OLinkman;
	private List<SiteCount> siteCounts = new ArrayList<SiteCount>(0);
	private List<Activities> activitieses = new ArrayList<Activities>(0);
	private List<Manager> managers = new ArrayList<Manager>(0);
	private List<VoucherStrategy> voucherStrategies = new ArrayList<VoucherStrategy>(0);

	public Long getOId() {
		return this.OId;
	}

	public void setOId(Long OId) {
		this.OId = OId;
	}

	public String getOName() {
		return this.OName;
	}

	public void setOName(String OName) {
		this.OName = OName;
	}

	public String getOCity() {
		return this.OCity;
	}

	public void setOCity(String OCity) {
		this.OCity = OCity;
	}

	public String getODistrict() {
		return this.ODistrict;
	}

	public void setODistrict(String ODistrict) {
		this.ODistrict = ODistrict;
	}

	public String getOAddress() {
		return this.OAddress;
	}

	public void setOAddress(String OAddress) {
		this.OAddress = OAddress;
	}

	public String getOTel() {
		return this.OTel;
	}

	public void setOTel(String OTel) {
		this.OTel = OTel;
	}

	public String getOZipcode() {
		return this.OZipcode;
	}

	public void setOZipcode(String OZipcode) {
		this.OZipcode = OZipcode;
	}

	public String getOLinkman() {
		return this.OLinkman;
	}

	public void setOLinkman(String OLinkman) {
		this.OLinkman = OLinkman;
	}

	public List<SiteCount> getSiteCounts() {
		return siteCounts;
	}

	public void setSiteCounts(List<SiteCount> siteCounts) {
		this.siteCounts = siteCounts;
	}

	public List<Activities> getActivitieses() {
		return activitieses;
	}

	public void setActivitieses(List<Activities> activitieses) {
		this.activitieses = activitieses;
	}

	public List<VoucherStrategy> getVoucherStrategies() {
		return voucherStrategies;
	}

	public void setVoucherStrategies(List<VoucherStrategy> voucherStrategies) {
		this.voucherStrategies = voucherStrategies;
	}

	public List<Manager> getManagers() {
		return managers;
	}

	public void setManagers(List<Manager> managers) {
		this.managers = managers;
	}

	public List<VoucherStrategy> getCoreVoucherStrategies() {
		return voucherStrategies;
	}

	public void setCoreVoucherStrategies(
			List<VoucherStrategy> voucherStrategies) {
		this.voucherStrategies = voucherStrategies;
	}

}
