package com.changh.exchange.entity.common;

// Generated 2014-11-6 14:03:33 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.reagan.core.annotation.Mapper;

/**
 * CommonRole generated by hbm2java
 */
@Mapper(tableName="common_role")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 276648735015873579L;
	@Mapper(column="r_id", updateWhere=true)
	private Long RId;
	@Mapper(column="r_name", update=true)
	private String RName;
	@Mapper(column="r_create_date", update=true)
	private Date RCreateDate;
	@Mapper(column="r_authority", update=true)
	private int RAuthority;
	private List<Manager> managers = new ArrayList<Manager>(0);

	
	public Long getRId() {
		return this.RId;
	}

	public void setRId(Long RId) {
		this.RId = RId;
	}

	public String getRName() {
		return this.RName;
	}

	public void setRName(String RName) {
		this.RName = RName;
	}

	public Date getRCreateDate() {
		return this.RCreateDate;
	}

	public void setRCreateDate(Date RCreateDate) {
		this.RCreateDate = RCreateDate;
	}

	public int getRAuthority() {
		return RAuthority;
	}

	public void setRAuthority(int rAuthority) {
		RAuthority = rAuthority;
	}

	public List<Manager> getManagers() {
		return managers;
	}

	public void setManagers(List<Manager> managers) {
		this.managers = managers;
	}
	
}
